"""
Hybrid query router for the TerraGuard AI Assistant.

Classifies each incoming question as needing:
  - "general_chat": a greeting/small-talk message ("hi", "thanks", "bye")
    with nothing to look up — answered instantly, no lookup/RAG/LLM call at all.
  - "about_app": a question about the application itself ("what is this
    app", "what's your name", "what can you do") — answered instantly from
    a fixed description, never guessed by an LLM or searched in the
    knowledge base (an LLM has no way to actually know "this app"'s name).
  - "structured": a real data lookup (risk zones, rainfall, landslide
    history) — numbers here are ALWAYS read directly from the Excel-backed
    in-memory store, never generated by an LLM.
  - "document": retrieval over knowledge_base/ (SOPs, guidance) via RAG.
  - "combined": both — structured facts are retrieved first, then handed to
    the LLM alongside document excerpts so it can explain them in context.

This is intentionally a lightweight keyword/regex classifier, not a trained
NLU model — appropriate for a bounded hackathon-scope assistant where the
question categories are known in advance (risk/rainfall/landslide-history
lookups vs. disaster-management guidance). It errs toward "document" when
unsure, which is the existing (already-safe) RAG fallback behavior.

Every structured_query() result is built ONLY from real rows in the Excel
store — if nothing matches, `found` is False and the caller must say so
explicitly rather than let the LLM guess.
"""
import re
from typing import Any, Literal, Optional

import pandas as pd

from app.core.excel_store import CENSUS_SYNTHETIC_PROVENANCE, Store
from app.services.rainfall_shock import DISTRICT_ALIASES

QuestionType = Literal["general_chat", "about_app", "structured", "document", "combined"]

NE_STATES = [
    "assam", "sikkim", "manipur", "meghalaya", "mizoram", "nagaland",
    "tripura", "arunachal pradesh",
]

MONTH_NAMES = {
    "january": 1, "february": 2, "march": 3, "april": 4, "may": 5, "june": 6,
    "july": 7, "august": 8, "september": 9, "october": 10, "november": 11, "december": 12,
}

STRUCTURED_KEYWORDS = [
    "risk score", "risk level", "risk zone", "highest risk", "most at risk", "most risky",
    "predicted risk", "risk of this location", "risk of", "how risky", "risk in", "risk at",
    "risk for", "current risk", "risk", "chance of landslide", "probability of landslide",
    "rainfall", "how much rain", "mm of rain", "precipitation",
    "how many landslide", "number of landslides", "landslide history", "landslide count",
    "historical landslide", "past landslide", "recent landslide", "recent landslides",
    "latest landslide", "latest landslides", "landslide events", "slope", "elevation",
    "latitude", "longitude", "coordinates",
    # Census 2001 village exposure/context data (village_census_profile) —
    # see docs/DATASET_SCHEMA_DIFF.md. Real rows only, same no-invented-
    # numbers rule as every other structured lookup.
    "population", "households", "how many people", "how many households",
    "village population", "census", "nearest town", "village directory",
]

DOCUMENT_KEYWORDS = [
    "should", "procedure", "guideline", "sop", "evacuat", "precaution",
    "respond", "response", "meaning", "what is", "define", "recommend",
    "action to take", "protocol", "warning sign", "prepare", "safety measure",
]

# Matched with a regex anchored to (mostly) the whole message, not a
# substring check — "hi" must not match inside "history" or "highest".
_GREETING_PATTERNS = [
    r"^h+[ie]y*!*$", r"^h+ello+!*$", r"^h+i+!*$", r"^hey+!*$",
    r"^good\s?(morning|afternoon|evening|night)!*$",
    r"^(yo|sup|namaste|hola)!*$",
    r"^thanks?( you)?!*$", r"^thank\s?you!*$", r"^ty!*$", r"^cheers!*$",
    r"^(bye|goodbye|see\s?you|see\s?ya|cya)!*$",
    r"^(ok|okay|cool|nice|great|got it|alright)!*$",
    r"^how are you\??$", r"^what'?s up\??$",
]

# Substring match is fine here — these phrases are specific enough that a
# false positive (matching inside an unrelated real question) is very
# unlikely, unlike the single-word greetings above.
_ABOUT_APP_PHRASES = [
    "name of this app", "name of the app", "this application's name",
    "what is this app", "what's this app", "what is this application",
    "what's this application", "who are you", "what are you",
    "what can you do", "what do you do", "tell me about yourself",
    "tell me about this app", "tell me about this application",
    "what is terraguard", "what's terraguard", "about terraguard",
    "which app is this", "what app is this", "your name",
]


_RECENCY_OR_COUNT_WORDS = (
    "recent", "latest", "any", "happened", "occurred", "occur", "history",
    "how many", "number of", "when", "did any", "was there", "were there",
)


def _mentions_landslide_event_lookup(q: str) -> bool:
    """True when the question is plainly asking about actual recorded
    landslide event(s) (e.g. "recent landslide in Assam", "any landslides
    near Dima Hasao", "landslide in Sikkim") rather than a conceptual
    question ("what is a landslide", "how do landslides happen"). Requires
    the bare word "landslide"/"landslides" PLUS either a named NE state or
    a recency/count word — this is deliberately narrower than a plain
    substring match on "landslide" alone so it doesn't misfire on
    definition/explanation questions, which have neither signal."""
    if "landslide" not in q:
        return False
    has_state = any(state in q for state in NE_STATES)
    has_recency_or_count = any(w in q for w in _RECENCY_OR_COUNT_WORDS)
    return has_state or has_recency_or_count


def classify_question(question: str) -> QuestionType:
    q = question.strip().lower()
    if any(re.fullmatch(pattern, q) for pattern in _GREETING_PATTERNS):
        return "general_chat"
    if any(phrase in q for phrase in _ABOUT_APP_PHRASES):
        return "about_app"
    has_structured = any(kw in q for kw in STRUCTURED_KEYWORDS) or _mentions_landslide_event_lookup(q)
    has_document = any(kw in q for kw in DOCUMENT_KEYWORDS)
    if has_structured and has_document:
        return "combined"
    if has_structured:
        return "structured"
    return "document"


def _extract_latlon(question: str) -> Optional[tuple[float, float]]:
    # Matches "25.17, 93.02" or "lat 25.17 lon 93.02" style mentions.
    m = re.search(r"(-?\d{1,2}\.\d+)\s*,\s*(-?\d{1,3}\.\d+)", question)
    if m:
        lat, lon = float(m.group(1)), float(m.group(2))
        if abs(lat) <= 90 and abs(lon) <= 180:
            return lat, lon
    return None


def _extract_state(question: str) -> Optional[str]:
    q = question.lower()
    for state in NE_STATES:
        if state in q:
            return state.title()
    return None


def _extract_district(store: Store, question: str) -> Optional[str]:
    q = question.lower()
    districts = set()
    for table in ("risk_zones", "landslide_events", "rainfall_records"):
        col = store.df(table).get("district")
        if col is not None:
            districts.update(col.dropna().unique().tolist())
    for district in districts:
        if district and str(district).lower() in q:
            return district
    return None


def _extract_month(question: str) -> Optional[int]:
    q = question.lower()
    for name, num in MONTH_NAMES.items():
        if name in q:
            return num
    return None


_CENSUS_STOPWORDS = {
    "How", "What", "Many", "People", "Live", "Near", "The", "Is", "In", "Of", "For",
    "Village", "Villages", "Population", "Households", "Census", "Town", "Nearest",
    "Please", "Tell", "Me", "About", "State", "District", "Total",
}


def _real_census_only(df: pd.DataFrame) -> pd.DataFrame:
    """The dataset's v2 expansion added transparently-labeled synthetic
    villages (data_provenance='synthetic_generated_v1') to
    village_census_profile — see excel_store.py's module docstring. Every
    RAG answer sourced from this table must stay real-data-only, exactly as
    it did before that expansion existed: a synthetic row's name/numbers
    are statistically modeled, not a real village, and must never be
    presented to a user as an actual Census 2001 record."""
    if "data_provenance" not in df.columns:
        return df
    return df[df["data_provenance"] != CENSUS_SYNTHETIC_PROVENANCE]


def _extract_village_name(store: Store, question: str) -> Optional[str]:
    """Village-name lookup against village_census_profile. This dataset has
    no coordinates and no shared key with any other table — village names
    are matched by text only, best-effort, never guessed. Tries each
    capitalized word/phrase in the ORIGINAL (not lowercased) question,
    longest first, so a real match beats a coincidental short one; returns
    the first that hits a real row."""
    state_names = {s.title() for s in NE_STATES}
    candidates = [
        w.strip("?,.!'\"")
        for w in question.split()
        if w[:1].isupper()
        and w.strip("?,.!'\"").title() not in _CENSUS_STOPWORDS
        and w.strip("?,.!'\"").title() not in state_names
        and len(w) >= 3
    ]
    df = _real_census_only(store.df("village_census_profile"))
    if df.empty:
        return None
    for word in sorted(set(candidates), key=len, reverse=True):
        match = df[df["village_name"].str.contains(word, case=False, na=False)]
        if not match.empty:
            return match.iloc[0]["village_name"]
    return None


def _census_query(store: Store, question: str) -> Optional[dict[str, Any]]:
    """Census 2001 village exposure/context data (village_census_profile) —
    population, households, and infrastructure, never risk/hazard data.
    Returns None (not a dict) when nothing census-shaped matched, so the
    caller falls through to its normal handling."""
    village = _extract_village_name(store, question)
    df = _real_census_only(store.df("village_census_profile"))
    if village:
        match = df[df["village_name"] == village]
        if not match.empty:
            row = match.iloc[0].to_dict()
            summary = (
                f"{row['village_name']} ({row['state_name']}) has a recorded population of "
                f"{row['population_total']} ({row['population_male']} male, {row['population_female']} female) "
                f"across {row['total_households']} households, per the Census of India 2001 Village Directory. "
                f"Nearest town: {row.get('nearest_town_name') or 'not recorded'}"
                + (f", {row['distance_to_town_km']} km away" if pd.notna(row.get("distance_to_town_km")) else "")
                + ". This is 2001 census exposure/context data — not a risk score, and not necessarily "
                "current population."
            )
            return {"found": True, "summary": summary, "rows": [row], "query_description": f"census profile for village {row['village_name']}"}

    state = _extract_state(question)
    if state:
        subset = df[df["state_name"].str.contains(state, case=False, na=False)] if not df.empty else df
        if not subset.empty:
            villages = len(subset)
            population_total = int(subset["population_total"].sum(skipna=True))
            total_households = int(subset["total_households"].sum(skipna=True))
            summary = (
                f"TerraGuard's Census 2001 Village Directory records {villages} villages in {state}, "
                f"with a combined recorded population of {population_total} across {total_households} "
                "households. This is 2001 census exposure/context data (no coordinates, not used for risk scoring) "
                "— see the Village Data tab for the full per-village breakdown."
            )
            return {
                "found": True, "summary": summary,
                "rows": [{"villages": villages, "population_total": population_total, "total_households": total_households}],
                "query_description": f"census aggregate for {state}",
            }
        return {
            "found": False,
            "authoritative": True,
            "summary": (
                f"TerraGuard's Census 2001 Village Directory dataset does not cover {state} "
                "(it covers Sikkim, Arunachal Pradesh, Nagaland, Mizoram, Tripura, Meghalaya, and Assam only — "
                "Manipur has no Village Directory file in this dataset)."
            ),
            "rows": [], "query_description": f"census aggregate for {state} (state not covered)",
        }

    return None


def _rainfall_district_names(district: Optional[str]) -> list[str]:
    if not district:
        return []
    names = [district]
    alias = DISTRICT_ALIASES.get(district)
    if alias and alias not in names:
        names.append(alias)
    return names


def _infer_state_for_district(store: Store, district: str) -> Optional[str]:
    d_lower = district.lower()
    for table in ("landslide_events", "risk_zones", "rainfall_records"):
        df = store.df(table)
        match = df[df["district"].astype("string").str.lower().str.contains(d_lower, na=False)]
        if not match.empty:
            return match.iloc[0]["state"]
    return None


_MONTH_LABELS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]


def _rainfall_heatmap(store: Store, district_names: list[str], state: Optional[str], max_years: int = 8) -> Optional[dict]:
    """Builds a year x month grid of REAL average rainfall (never invented —
    every cell is a mean over actual rainfall_records rows) for whichever
    place the question resolved to. Returns None when there isn't enough
    real history to make a meaningful grid (fewer than 2 distinct years)."""
    df = store.df("rainfall_records")
    df = df[df["rainfall_mm"].notna()]
    if district_names:
        mask = df["district"].astype("string").str.contains("|".join(re.escape(n) for n in district_names), case=False, na=False)
        df = df[mask]
    elif state:
        df = df[df["state"].astype("string").str.contains(state, case=False, na=False)]
    else:
        return None

    years = sorted(df["year"].dropna().unique().tolist(), reverse=True)[:max_years]
    if len(years) < 2:
        return None
    years = sorted(int(y) for y in years)

    subset = df[df["year"].isin(years)]
    grid = subset.groupby(["year", "month"])["rainfall_mm"].mean().round(1).to_dict()
    values = [[grid.get((y, m)) for m in range(1, 13)] for y in years]
    return {
        "type": "heatmap",
        "title": "Monthly rainfall (mm), by year — real recorded averages",
        "x_labels": _MONTH_LABELS,
        "y_labels": [str(y) for y in years],
        "values": values,
        "unit": "mm",
    }


def _state_month_rainfall_estimate(store: Store, state: str, month: Optional[int]) -> Optional[dict]:
    """A real-data statistical fallback (median monthly rainfall, computed
    from actual recorded rows for the state) — used only when a specific
    district has zero real records."""
    df = store.df("rainfall_records")
    df = df[df["state"].astype("string").str.contains(state, case=False, na=False) & df["rainfall_mm"].notna()]
    if month:
        df = df[df["month"] == month]
    if df.empty:
        return None
    return {"count": len(df), "median_mm": round(float(df["rainfall_mm"].median()), 1)}


def structured_query(store: Store, question: str) -> dict[str, Any]:
    """Runs the appropriate real lookup for a structured question against
    the Excel-backed in-memory store. Returns {found, summary, rows,
    query_description} — `summary` is built only from the returned rows,
    never invented."""
    q = question.lower()
    latlon = _extract_latlon(question)
    state = _extract_state(question)
    district = _extract_district(store, question)
    month = _extract_month(question)

    # --- Slope is explicitly NOT tracked — say so rather than guessing.
    if "slope" in q and "risk" not in q:
        return {
            "found": False,
            "authoritative": True,
            "summary": (
                "TerraGuard's data does not currently store slope-angle values for locations — "
                "only latitude/longitude, ML-derived risk scores, and monthly rainfall are tracked. "
                "This question cannot be answered from available TerraGuard data."
            ),
            "rows": [],
            "query_description": "slope lookup (not available)",
        }

    # --- Census 2001 village exposure/context data ---
    if any(kw in q for kw in ["population", "household", "census", "nearest town", "village directory", "how many people"]):
        census_result = _census_query(store, question)
        if census_result is not None:
            return census_result

    zones_df = store.df("risk_zones")

    # --- Highest / most-at-risk area ---
    if any(kw in q for kw in ["highest risk", "most at risk", "most risky", "top risk"]):
        rows = zones_df.sort_values("risk_score", ascending=False).head(5)
        rows = rows[["name", "state", "district", "risk_score", "risk_level", "updated_at"]].to_dict("records")
        if not rows:
            return {"found": False, "summary": "No risk zones are currently recorded.", "rows": [], "query_description": "highest risk zones"}
        top = rows[0]
        summary = (
            f"The highest recorded risk zone is {top['name'] or 'an unnamed zone'} "
            f"({top['district'] or top['state'] or 'location unspecified'}), "
            f"with a risk score of {top['risk_score']} ({top['risk_level']})."
        )
        return {"found": True, "summary": summary, "rows": rows, "query_description": "highest risk zones (from risk_zones table)"}

    # --- Risk at a specific coordinate ---
    if latlon and ("risk" in q or "predicted risk" in q):
        lat, lon = latlon
        if zones_df.empty:
            return {"found": False, "summary": "No risk zones are recorded near that location.", "rows": [], "query_description": "nearest risk zone"}
        from app.services import geo_utils
        nearest = geo_utils.nearest_one(zones_df, lat, lon)
        row = dict(nearest)
        summary = (
            f"The nearest recorded risk zone to ({lat}, {lon}) is {row['name'] or 'an unnamed zone'} "
            f"in {row['district'] or row['state']}, about {round(row['distance_m'] / 1000, 1)} km away, "
            f"with risk score {row['risk_score']} ({row['risk_level']}). "
            "For a fresh live model prediction at an exact point (using current month + rainfall), "
            "use the Prediction page instead — this is the nearest already-computed risk zone, not a new model run."
        )
        return {"found": True, "summary": summary, "rows": [row], "query_description": "nearest stored risk zone to given coordinates"}

    # --- Risk for a named district/state ---
    if (district or state) and ("risk" in q):
        rows = zones_df
        mask = pd.Series(False, index=rows.index)
        if district:
            mask |= rows["district"].astype("string").str.contains(district, case=False, na=False)
        if state:
            mask |= rows["state"].astype("string").str.contains(state, case=False, na=False)
        rows = rows[mask].sort_values("risk_score", ascending=False).head(5)
        rows = rows[["name", "state", "district", "risk_score", "risk_level"]].to_dict("records")
        place = district or state
        if not rows:
            return {"found": False, "summary": f"No risk zones are recorded for {place}.", "rows": [], "query_description": f"risk zones in {place}"}
        top = rows[0]
        summary = f"In {place}, the highest recorded risk zone is {top['name'] or 'an unnamed zone'} with risk score {top['risk_score']} ({top['risk_level']})."
        return {"found": True, "summary": summary, "rows": rows, "query_description": f"risk zones in {place}"}

    # --- Generic "what is the current risk" with no location given ---
    # A bare current/present-tense risk question ("What is the current
    # landslide risk?") with no state/district/coordinates to filter by is
    # best answered the same honest way as an explicit "highest risk"
    # question — a real region-wide overview from risk_zones — rather than
    # falling through empty and relying on document search to happen to
    # find something relevant. Deliberately narrow and excludes explanation
    # ("explain", "how does X work", "predict", "factors") so a genuinely
    # conceptual question about the methodology still goes to document
    # retrieval instead of being answered with a specific zone's number.
    if (
        "risk" in q and not district and not state and not latlon
        and any(w in q for w in ("current", "currently", "right now", "at the moment", " now"))
        and not any(w in q for w in ("explain", "how does", "how is", "how do", "why", "factor", "predict", "methodology", "algorithm", "how terraguard"))
    ):
        rows = zones_df.sort_values("risk_score", ascending=False).head(5)
        rows = rows[["name", "state", "district", "risk_score", "risk_level", "updated_at"]].to_dict("records")
        if not rows:
            return {"found": False, "summary": "No risk zones are currently recorded.", "rows": [], "query_description": "current risk overview"}
        top = rows[0]
        critical_or_high = [r for r in rows if str(r["risk_level"]).upper() in ("HIGH", "CRITICAL")]
        summary = (
            f"Across TerraGuard's currently recorded risk zones, the highest is {top['name'] or 'an unnamed zone'} "
            f"({top['district'] or top['state'] or 'location unspecified'}) with a risk score of {top['risk_score']} "
            f"({top['risk_level']}). {len(critical_or_high)} of the top zones shown are HIGH/CRITICAL. "
            "Ask about a specific state or district (e.g. \"risk in Dima Hasao\") for a location-specific answer, "
            "or open the GIS Map for the full picture."
        )
        return {"found": True, "summary": summary, "rows": rows, "query_description": "current risk overview (no location specified)"}

    # --- Rainfall ---
    if any(kw in q for kw in ["rainfall", "how much rain", "mm of rain", "precipitation"]):
        df = store.df("rainfall_records")
        district_names = _rainfall_district_names(district)
        mask = pd.Series(True, index=df.index)
        applied_filter = False
        if district_names:
            mask &= df["district"].astype("string").str.contains("|".join(re.escape(n) for n in district_names), case=False, na=False)
            applied_filter = True
        if state:
            mask &= df["state"].astype("string").str.contains(state, case=False, na=False)
            applied_filter = True
        if month:
            mask &= df["month"] == month
        if not applied_filter:
            return {
                "found": False,
                "summary": "Please specify a state or district to look up rainfall data (e.g. \"rainfall in Dima Hasao\").",
                "rows": [], "query_description": "rainfall (no location given)",
            }
        rows_df = df[mask].sort_values(["year", "month"], ascending=False).head(5)
        rows = rows_df[["state", "district", "year", "month", "rainfall_mm", "data_provenance"]].to_dict("records")
        place = district or state
        if rows:
            top = rows[0]
            summary = f"The most recent recorded rainfall for {place} is {top['rainfall_mm']} mm ({top['year']}-{top['month']:02d}, {top['data_provenance']} data)."
            chart_data = _rainfall_heatmap(store, district_names, state)
            return {"found": True, "summary": summary, "rows": rows, "query_description": f"rainfall records for {place}", "chart_data": chart_data}

        fallback_state = state or (_infer_state_for_district(store, district) if district else None)
        if fallback_state:
            est = _state_month_rainfall_estimate(store, fallback_state, month)
            if est:
                summary = (
                    f"TerraGuard has no rainfall records specifically for {place}"
                    + (f" in month {month}" if month else "")
                    + f". Based on {est['count']} real recorded IMD rainfall values across {fallback_state}"
                    + (f" for month {month}" if month else "")
                    + f", the typical (median) monthly rainfall is approximately {est['median_mm']} mm. "
                    "This is a state-level estimate from real data, not a district-specific measurement."
                )
                chart_data = _rainfall_heatmap(store, [], fallback_state)
                return {
                    "found": True,
                    "summary": summary,
                    "rows": [],
                    "query_description": f"state-level rainfall estimate for {place} (no district-specific records)",
                    "chart_data": chart_data,
                }

        return {"found": False, "summary": f"No rainfall records are available for {place}" + (f" in month {month}" if month else "") + ".", "rows": [], "query_description": f"rainfall in {place}"}

    # --- Landslide history / counts ---
    if any(kw in q for kw in [
        "how many landslide", "number of landslides", "landslide history", "landslide count",
        "historical landslide", "past landslide", "recent landslide", "recent landslides",
        "latest landslide", "latest landslides", "landslide events",
    ]) or _mentions_landslide_event_lookup(q):
        df = store.df("landslide_events")
        mask = pd.Series(True, index=df.index)
        if district:
            mask &= df["district"].astype("string").str.contains(district, case=False, na=False)
        if state:
            mask &= df["state"].astype("string").str.contains(state, case=False, na=False)
        subset = df[mask]
        count = len(subset)
        rows = subset.sort_values("event_date", ascending=False, na_position="last").head(5)
        rows = rows[["event_title", "state", "district", "event_date", "severity", "trigger"]].to_dict("records")
        place = district or state or "the North East India region"
        summary = f"TerraGuard's historical dataset records {count} landslide event(s) for {place}."
        return {"found": count > 0, "summary": summary, "rows": rows, "query_description": f"landslide event history for {place}"}

    return {"found": False, "summary": "", "rows": [], "query_description": "no structured handler matched"}
